### ISSUE TITLE
confusion about datasets

### ISSUE THREAD

**Issue by zxr19980213** [HKUST-KnowComp/FKGE#1]
i see from readme that the datasets have been uploaded but i cannot find.
i run the project with provided script and the error information is "No such file or directory: './OpenKE/benchmarks/geonames_1/entity2id.txt'"
is there any step followed wrongly by me?

**Comment by teapotliid** [comment]
Sorry for the late reply. You can find all the data at the following link: https://drive.google.com/file/d/1oD1Gv2RbpNzO8GWGq7SusbAmYih5r-6Q/view?usp=sharing

**Comment by zxr19980213** [comment]
Thank you very much!
