### ISSUE TITLE
Where is align.npy

### ISSUE THREAD

**Issue by abxboy** [HKUST-KnowComp/FKGE#2]
Hello, I can't find the file align. npy, and I also found train_ The data/aligned/path does not exist. Is the file path generator included in FKGE?

**Comment by orion-orion** [comment]
Hey man, I've been following this project for a long time, his code is so badly written, I don't think there is need to waste time running it.

**Comment by orion-orion** [comment]
> Hello, I can't find the file align. npy, and I also found train_ The data/aligned/path does not exist. Is the file path generator included in FKGE?

Hey man, I've been following this project for a long time, his code is so badly written, I don't think there is need to waste time running it.

**Comment by abxboy** [comment]
> > Hello, I can't find the file align. npy, and I also found train_ The data/aligned/path does not exist. Is the file path generator included in FKGE?
> 
> Hey man, I've been following this project for a long time, his code is so badly written, I don't think there is need to waste time running it.
Thank you. This project has also troubled me for a long time. Now I decide not to spend time on it

**Comment by teapotliid** [comment]
> > > Hello, I can't find the file align. npy, and I also found train_ The data/aligned/path does not exist. Is the file path generator included in FKGE?
> > 
> > 
> > Hey man, I've been following this project for a long time, his code is so badly written, I don't think there is need to waste time running it.
> > Thank you. This project has also troubled me for a long time. Now I decide not to spend time on it

It seems that the align part is missing, tomorrow I will upload it and rewrite a clearer Readme file to guide you to run FKGE step by step. My apology for the missing align files.
