### ISSUE TITLE
Where is intersection in ‘'./OpenKE/benchmarks/geonames_1/’？ 

### ISSUE THREAD

**Issue by orion-orion** [HKUST-KnowComp/FKGE#3]
In hetro_init.py, line 21
```python
for kg in all_kg:
        path = './OpenKE/benchmarks/' + kg + '_1/intersection'
        for f in os.listdir(path):
```
where is ‘'./OpenKE/benchmarks/geonames_1/intersection’？

**Comment by teapotliid** [comment]
Please check our updated readme. Some codes are historical files for experiments not reported in the paper. You can simply ignore this file and follow our instructions to run FKGE.
