### ISSUE TITLE
Where is 'subgeonamesA.txt'?

### ISSUE THREAD

**Issue by orion-orion** [HKUST-KnowComp/FKGE#4]
In initializer.py, line 34:
```python
  with open(os.path.join('experiment', str(pred_id), 'result', kg + '.txt')) as fp:
      line = fp.readline().strip()
```
Where is 'experiment/2/result/subgeonamesA.txt'?

**Comment by teapotliid** [comment]
> In initializer.py, line 34:
> 
> ```python
>   with open(os.path.join('experiment', str(pred_id), 'result', kg + '.txt')) as fp:
>       line = fp.readline().strip()
> ```
> 
> Where is 'experiment/2/result/subgeonamesA.txt'?

`subgeonamesA.txt` is used as our ablation study since we split the `geonames` into two parts. You can find the code in `split.py` (https://github.com/HKUST-KnowComp/FKGE/blob/main/split.py).
