### ISSUE TITLE
The code is so bad

### ISSUE THREAD

**Issue by orion-orion** [HKUST-KnowComp/FKGE#5]
In deal.py, line 48:
```python
for aligned_file_name in os.list_dir(os.path.join('trainse_data', 'aligned'))
```

You call `os.list_dir()`, what is that? The correct function should be `os.listdir()`!

and in line 41:
```python
        line = [line.split('\t')]
        e1, e2, edge = line[0], line[1], line[2]
```
`split` function will return a list itself, why do you use a `[]` to put a list in a list?

**Comment by marcos0318** [comment]
Man, if you don't like the thing, you can have a pull request.

**Comment by yqsong** [comment]
Hi Jiaxin, there is no need to argue. I have contacted Haoran and Hao to refactor the code to make it easier to use.

**Comment by teapotliid** [comment]
> In deal.py, line 48:
> 
> ```python
> for aligned_file_name in os.list_dir(os.path.join('trainse_data', 'aligned'))
> ```
> 
> You call `os.list_dir()`, what the hell is that? The correct function should be `os.listdir()`!
> 
> and in line 41:
> 
> ```python
>         line = [line.split('\t')]
>         e1, e2, edge = line[0], line[1], line[2]
> ```
> 
> `split` function will return a list itself, why do you use a `[]` to put a list in a list?

I think this [deal_kg.py](https://github.com/HKUST-KnowComp/FKGE/blob/main/deal_kg.py) is not called for our experiments, they are just some historical files. Maybe I will check and delete them to avoid confusion.
